services:
  db:
    image: postgres:17-alpine
    container_name: vet-manager-db
    environment:
      POSTGRES_DB: vet_manager_db
      POSTGRES_USER: lucas_dev
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: