spring:
  application:
    name: vet-manager-api

  profiles:
    active: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

vet:
  security:
    jwt:
      public-key: classpath:${JWT_PUBLIC_KEY_PATH}
      private-key: classpath:${JWT_PRIVATE_KEY_PATH}