spring:
  application:
    name: vet-manager-api

  profiles:
    active: dev

  jwt:
    public:
      key: ${JWT_PUBLIC_KEY_PATH}
    private:
      key: ${JWT_PRIVATE_KEY_PATH}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true